python train_diffusion.py ^
    --dataset_name PMMA ^
    --output_dir results ^
    --resolution 256 ^
    --train_batch_size 4 ^
    --eval_batch_size 4 ^
    --dataloader_num_workers 0 ^
    --num_epochs 1000 ^
    --save_images_epochs 5 ^
    --save_model_epochs 5 ^
    --gradient_accumulation_steps 4 ^
    --learning_rate 1e-4 ^
    --use_ema ^
    --logger tensorboard ^
    --cache_dir .\.cache ^
    --checkpointing_steps 5000 ^
    --enable_xformers_memory_efficient_attention
